name: oecd-housing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adjusttext=0.7.3.1
  - beautifulsoup4=4.11.1
  - black=22.12.0
  - docopt=0.6.2
  - ipython=8.8.0
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - numpy=1.24.1
  - pandas=1.5.3
  - pip=22.3.1
  - python=3.11.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - statsmodels=0.13.5
